# Generated by Django 4.0.1 on 2022-01-23 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_maincontent_sub_topic_subcontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubContent',
        ),
    ]
