# Generated by Django 4.0.1 on 2022-01-24 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_subcontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubContent',
        ),
    ]
