# Generated by Django 4.0.1 on 2022-01-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_delete_subcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontent',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
