# Generated by Django 4.0.1 on 2022-01-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_maincontent_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontent',
            name='estimated_time',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='maincontent',
            name='sub_topic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
