# Generated by Django 4.0.1 on 2022-01-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_maincontent_estimated_time_maincontent_sub_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincontent',
            name='estimated_time',
            field=models.BigIntegerField(default=1, null=True),
        ),
    ]
