# Generated by Django 4.0.1 on 2022-01-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_maincontent_estimated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincontent',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maincontent',
            name='estimated_time',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='maincontent',
            name='sub_topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
