# Generated by Django 4.0.1 on 2022-01-27 02:00

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_maincontent_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontent',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default=None, editable=False, null=True, populate_from='topic', unique=True),
        ),
    ]
