# Generated by Django 4.0.1 on 2022-01-27 03:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_subcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontent',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
