# Generated by Django 4.0.1 on 2022-01-27 03:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_subcontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincontent',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
