# Generated by Django 4.0.1 on 2022-01-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_maincontent_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubContent',
        ),
    ]
