# Generated by Django 4.0.1 on 2022-01-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_question', models.IntegerField()),
                ('time', models.FloatField(help_text='Duration of the quiz in minutes')),
            ],
        ),
    ]
