# Generated by Django 4.0.1 on 2022-01-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Test', '0002_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_question', models.IntegerField()),
            ],
        ),
    ]
