# Generated by Django 4.0.1 on 2022-01-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestManagement',
        ),
    ]
