# Generated by Django 4.0.1 on 2022-01-27 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0014_delete_subcontent'),
        ('Test', '0004_delete_testmanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_question', models.IntegerField()),
                ('time', models.FloatField(help_text='Duration of the quiz in minutes')),
                ('pass_marks', models.FloatField(help_text='Passmarks for test')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.maincontent')),
            ],
        ),
    ]
