# Generated by Django 4.0.1 on 2022-01-27 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmanagement',
            name='time',
            field=models.FloatField(help_text='Duration of the test in minutes'),
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.testmanagement')),
            ],
        ),
    ]
