# Generated by Django 4.0.1 on 2022-01-27 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0006_alter_testmanagement_time_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('correct_answer', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.questions')),
            ],
        ),
    ]
