# Generated by Django 4.0.1 on 2022-01-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0008_results'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmanagement',
            options={'verbose_name': 'Test Management'},
        ),
    ]
