# Generated by Django 4.0.1 on 2022-01-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0009_alter_testmanagement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name_plural': 'Test Answers'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name_plural': 'Test Questions'},
        ),
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name_plural': 'Test Results'},
        ),
        migrations.AlterModelOptions(
            name='testmanagement',
            options={'verbose_name_plural': 'Test Management'},
        ),
    ]
