# Generated by Django 4.0.1 on 2022-01-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0010_alter_answers_options_alter_questions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='correct_answer',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
