# Generated by Django 3.2.9 on 2022-01-29 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0011_alter_answers_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='test',
        ),
        migrations.RemoveField(
            model_name='results',
            name='test',
        ),
        migrations.RemoveField(
            model_name='results',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testmanagement',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Results',
        ),
        migrations.DeleteModel(
            name='TestManagement',
        ),
    ]
