# Generated by Django 4.0.1 on 2022-02-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmanagement',
            name='required_score_to_pass',
            field=models.IntegerField(default=50, help_text='required score in %'),
        ),
    ]
