# Generated by Django 4.0.1 on 2022-01-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preregistration',
            old_name='password1',
            new_name='password',
        ),
    ]
