# Generated by Django 4.0.1 on 2022-01-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=300)),
            ],
        ),
    ]
