version: '3.4'
services:
  rasa:
    build: .
    working_dir: /app
    # volumes:
    # - ./:./app
    # - ./data:/app/data
    command: bash -c "rm -rf models/* && rasa train && rasa run --enable-api --cors \"*\" --debug"
    ports:
    - '5005:5005'
    networks:
    - all

  rasa-actions:
    build: .
    working_dir: /app
    volumes:
    - ./actions:/app/actions
    - ./utils:/app/utils
    command: ["rasa", "run", "actions"]
    ports:
    - '5055:5055'
    networks:
    - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"